export const allItems = [
    {_id:1,title: "All Categroies"},
    {_id:2,title: "Alexa Skills"},
    {_id:3,title: "Amazon Devices"},
    {_id:4,title: "Amazon Fashion"},
    {_id:5,title: "Amazon Fresh"},
    {_id:6,title: "Amazon Pharmacy"},
    {_id:7,title: "Appliances"},
    {_id:8,title: "Apps & Games"},
    {_id:9,title: "Baby"},
    {_id:10,title: "Beauty"},
    {_id:11,title: "Books"},
    {_id:12,title: "Car & Moterbike"},
    {_id:13,title: "Clothing"},
    {_id:14,title: "Computers"},
    {_id:15,title: "Electronics"},
    {_id:16,title: "Furniture"},
    {_id:17,title: "Garden & Outdoors"},
    {_id:18,title: "Gifts"},
    {_id:19,title: "Groceries"},
    {_id:20,title: "Health & Personal Care"},
    {_id:21,title: "Home & Kitchen"},
    {_id:22,title: "Jewellery"},
    {_id:23,title: "Kindle Store"},
    {_id:24,title: "Luggage & Bags"},
    {_id:25,title: "Luxury Beauty"},
    {_id:26,title: "Movies & Shows"},
    {_id:27,title: "Music"},
    {_id:28,title: "Office Products"},
    {_id:29,title: "Pet Supplies"},
    {_id:30,title: "Shoes and HandBags"},
    {_id:31,title: "Softwares"},
    {_id:32,title: "Toys & Games"},
    {_id:33,title: "Under 500"},
    {_id:34,title: "Watches"}
    
];